# Form implementation generated from reading ui file 'c:\Users\binhn\Documents\MindX\PTI\PTI-02-HB\PTI_TungNam_DaiKhang\ui\item.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(339, 547)
        self.movieView = QtWidgets.QLabel(parent=Form)
        self.movieView.setGeometry(QtCore.QRect(10, 10, 311, 391))
        self.movieView.setText("")
        self.movieView.setObjectName("movieView")
        self.movieTitle = QtWidgets.QLabel(parent=Form)
        self.movieTitle.setGeometry(QtCore.QRect(10, 410, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.movieTitle.setFont(font)
        self.movieTitle.setObjectName("movieTitle")
        self.movieInfo = QtWidgets.QLabel(parent=Form)
        self.movieInfo.setGeometry(QtCore.QRect(10, 470, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.movieInfo.setFont(font)
        self.movieInfo.setObjectName("movieInfo")
        self.movieRating = QtWidgets.QLabel(parent=Form)
        self.movieRating.setGeometry(QtCore.QRect(170, 470, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.movieRating.setFont(font)
        self.movieRating.setObjectName("movieRating")
        self.movieGenre = QtWidgets.QLabel(parent=Form)
        self.movieGenre.setGeometry(QtCore.QRect(10, 510, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.movieGenre.setFont(font)
        self.movieGenre.setObjectName("movieGenre")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.movieTitle.setText(_translate("Form", "Title"))
        self.movieInfo.setText(_translate("Form", "Release date"))
        self.movieRating.setText(_translate("Form", "Rating: "))
        self.movieGenre.setText(_translate("Form", "Genre"))
