# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user_info.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(751, 571)
        font = QFont()
        font.setPointSize(11)
        font.setBold(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.widget = QWidget(MainWindow)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 751, 571))
        self.widget.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label = QLabel(self.widget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, 10, 121, 31))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"color:rgb(0, 0, 0);")
        self.widget_2 = QWidget(self.widget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(19, 49, 721, 91))
        self.widget_2.setStyleSheet(u"border-radius: 10px;\n"
"background-color: rgb(238, 238, 238);")
        self.label_15 = QLabel(self.widget_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(640, 10, 151, 81))
        self.label_15.setPixmap(QPixmap(u"../img/leavecenter.png"))
        self.label_15.setScaledContents(True)
        self.label_20 = QLabel(self.widget_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(350, 40, 101, 131))
        self.label_20.setStyleSheet(u"border-radius: 10px;")
        self.label_20.setPixmap(QPixmap(u"../img/leaves diagonal1.png"))
        self.label_20.setScaledContents(True)
        self.avatarBtn = QPushButton(self.widget_2)
        self.avatarBtn.setObjectName(u"avatarBtn")
        self.avatarBtn.setGeometry(QRect(20, 0, 121, 91))
        icon = QIcon()
        icon.addFile(u"../img/\u0111\u00e3 v\u1ebd02.png", QSize(), QIcon.Normal, QIcon.Off)
        self.avatarBtn.setIcon(icon)
        self.avatarBtn.setIconSize(QSize(121, 91))
        self.widget_3 = QWidget(self.widget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(20, 150, 711, 381))
        self.widget_3.setFont(font)
        self.widget_3.setStyleSheet(u"border-radius: 10px;\n"
"background-color: rgb(238, 238, 238);")
        self.label_2 = QLabel(self.widget_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 10, 531, 41))
        font2 = QFont()
        font2.setPointSize(17)
        font2.setBold(True)
        self.label_2.setFont(font2)
        self.label_2.setStyleSheet(u"color:rgb(0, 0, 0);")
        self.label_4 = QLabel(self.widget_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 100, 61, 31))
        font3 = QFont()
        font3.setPointSize(13)
        font3.setBold(True)
        self.label_4.setFont(font3)
        self.label_4.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.txtEmail = QLineEdit(self.widget_3)
        self.txtEmail.setObjectName(u"txtEmail")
        self.txtEmail.setGeometry(QRect(160, 100, 221, 41))
        self.txtEmail.setFont(font3)
        self.txtEmail.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_5 = QLabel(self.widget_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 50, 121, 31))
        self.label_5.setFont(font3)
        self.label_5.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.txtName = QLineEdit(self.widget_3)
        self.txtName.setObjectName(u"txtName")
        self.txtName.setGeometry(QRect(160, 50, 221, 41))
        self.txtName.setFont(font3)
        self.txtName.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_6 = QLabel(self.widget_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 150, 101, 31))
        self.label_6.setFont(font3)
        self.label_6.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.txtPass = QLineEdit(self.widget_3)
        self.txtPass.setObjectName(u"txtPass")
        self.txtPass.setGeometry(QRect(160, 150, 221, 41))
        self.txtPass.setFont(font3)
        self.txtPass.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_7 = QLabel(self.widget_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 200, 71, 31))
        self.label_7.setFont(font3)
        self.label_7.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.txtPhone = QLineEdit(self.widget_3)
        self.txtPhone.setObjectName(u"txtPhone")
        self.txtPhone.setGeometry(QRect(160, 200, 221, 41))
        self.txtPhone.setFont(font3)
        self.txtPhone.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_8 = QLabel(self.widget_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 250, 91, 21))
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.txtAddress = QLineEdit(self.widget_3)
        self.txtAddress.setObjectName(u"txtAddress")
        self.txtAddress.setGeometry(QRect(160, 250, 221, 41))
        self.txtAddress.setFont(font3)
        self.txtAddress.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.label_9 = QLabel(self.widget_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 300, 121, 31))
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.txtCountry = QLineEdit(self.widget_3)
        self.txtCountry.setObjectName(u"txtCountry")
        self.txtCountry.setGeometry(QRect(160, 300, 221, 41))
        self.txtCountry.setFont(font3)
        self.txtCountry.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.saveBtn = QPushButton(self.widget_3)
        self.saveBtn.setObjectName(u"saveBtn")
        self.saveBtn.setGeometry(QRect(460, 300, 221, 41))
        font4 = QFont()
        font4.setPointSize(16)
        font4.setBold(True)
        self.saveBtn.setFont(font4)
        self.saveBtn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(0, 170, 0);")
        self.resetBtn = QPushButton(self.widget_3)
        self.resetBtn.setObjectName(u"resetBtn")
        self.resetBtn.setGeometry(QRect(460, 250, 221, 41))
        self.resetBtn.setFont(font4)
        self.resetBtn.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);")
        self.label_18 = QLabel(self.widget_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(610, -10, 121, 91))
        self.label_18.setStyleSheet(u"border-radius: 10px;")
        self.label_18.setPixmap(QPixmap(u"../img/leaves-horizontal.png"))
        self.label_18.setScaledContents(True)
        self.label_21 = QLabel(self.widget_3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(350, -60, 101, 121))
        self.label_21.setStyleSheet(u"border-radius: 10px;")
        self.label_21.setPixmap(QPixmap(u"../img/leaves diagonal1.png"))
        self.label_21.setScaledContents(True)
        self.label_22 = QLabel(self.widget_3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(340, 310, 101, 131))
        self.label_22.setStyleSheet(u"border-radius: 10px;")
        self.label_22.setPixmap(QPixmap(u"../img/leaves diagonal1.png"))
        self.label_22.setScaledContents(True)
        self.label_22.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.txtEmail.raise_()
        self.label_5.raise_()
        self.txtName.raise_()
        self.label_6.raise_()
        self.txtPass.raise_()
        self.label_7.raise_()
        self.txtPhone.raise_()
        self.label_8.raise_()
        self.txtAddress.raise_()
        self.label_9.raise_()
        self.txtCountry.raise_()
        self.saveBtn.raise_()
        self.resetBtn.raise_()
        self.label_18.raise_()
        self.label_21.raise_()
        self.label_10 = QLabel(self.widget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(660, -40, 121, 91))
        self.label_10.setStyleSheet(u"border-radius: 10px;")
        self.label_10.setPixmap(QPixmap(u"../img/leaves-horizontal.png"))
        self.label_10.setScaledContents(True)
        self.label_11 = QLabel(self.widget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(110, -30, 101, 131))
        self.label_11.setStyleSheet(u"border-radius: 10px;")
        self.label_11.setPixmap(QPixmap(u"../img/leaves diagonal1.png"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(470, 510, 101, 131))
        self.label_12.setStyleSheet(u"border-radius: 10px;")
        self.label_12.setPixmap(QPixmap(u"../img/leaves diagonal1.png"))
        self.label_12.setScaledContents(True)
        self.label_13 = QLabel(self.widget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(200, 480, 121, 91))
        self.label_13.setStyleSheet(u"border-radius: 10px;")
        self.label_13.setPixmap(QPixmap(u"../img/leaves-horizontal.png"))
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.widget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(270, -50, 121, 91))
        self.label_14.setStyleSheet(u"border-radius: 10px;")
        self.label_14.setPixmap(QPixmap(u"../img/leaves-horizontal.png"))
        self.label_14.setScaledContents(True)
        self.label_16 = QLabel(self.widget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(60, 520, 151, 81))
        self.label_16.setPixmap(QPixmap(u"../img/leavecenter.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.widget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(460, 10, 151, 81))
        self.label_17.setPixmap(QPixmap(u"../img/leavecenter.png"))
        self.label_17.setScaledContents(True)
        self.label_19 = QLabel(self.widget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(660, 530, 151, 81))
        self.label_19.setPixmap(QPixmap(u"../img/leavecenter.png"))
        self.label_19.setScaledContents(True)
        self.label_17.raise_()
        self.label_13.raise_()
        self.label_12.raise_()
        self.label_11.raise_()
        self.label_10.raise_()
        self.label.raise_()
        self.widget_2.raise_()
        self.widget_3.raise_()
        self.label_14.raise_()
        self.label_16.raise_()
        self.label_19.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"My Profile", None))
        self.label_15.setText("")
        self.label_20.setText("")
        self.avatarBtn.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Personal Information", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Email", None))
        self.txtEmail.setText("")
        self.txtEmail.setPlaceholderText(QCoreApplication.translate("MainWindow", u"User1@gmail.com", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Username", None))
        self.txtName.setPlaceholderText(QCoreApplication.translate("MainWindow", u"User1", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.txtPass.setPlaceholderText(QCoreApplication.translate("MainWindow", u"*********", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Phone", None))
        self.txtPhone.setPlaceholderText("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Address", None))
        self.txtAddress.setPlaceholderText(QCoreApplication.translate("MainWindow", u"69/96 TranDuyHung", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Nationality", None))
        self.txtCountry.setPlaceholderText(QCoreApplication.translate("MainWindow", u"VietNam", None))
        self.saveBtn.setText(QCoreApplication.translate("MainWindow", u"SAVE", None))
        self.resetBtn.setText(QCoreApplication.translate("MainWindow", u"RESET", None))
        self.label_18.setText("")
        self.label_21.setText("")
        self.label_22.setText("")
        self.label_10.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_19.setText("")
    # retranslateUi

